apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-db
spec:
  replicas: {{ .Values.movieDb.replicaCount }}
  selector:
    matchLabels:
      app: movie-db
  template:
    metadata:
      labels:
        app: movie-db
    spec:
      containers:
        - name: movie-db
          image: "{{ .Values.movieDb.image.repository }}:{{ .Values.movieDb.image.tag }}"
          ports:
            - containerPort: {{ .Values.movieDb.port }}
          env:
            - name: POSTGRES_USER
              value: "{{ .Values.movieDb.env.postgresUser }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.movieDb.env.postgresPassword }}"
            - name: POSTGRES_DB
              value: "{{ .Values.movieDb.env.postgresDb }}"
          volumeMounts:
            - name: postgres-data-movie
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data-movie
          persistentVolumeClaim:
            claimName: postgres-data-movie
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "movies.fullname" . }}
  labels:
    {{- include "movies.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "movies.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "movies.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "movies.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000", "--loop", "asyncio"]
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: DATABASE_URI
              value: "postgresql://{{ .Values.movieDb.env.postgresUser }}:{{ .Values.movieDb.env.postgresPassword }}@movie-db/{{ .Values.movieDb.env.postgresDb }}"
            - name: CAST_SERVICE_HOST_URL
              value: "{{ .Values.env.castServiceHostUrl }}"
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-movie
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.movieDb.storage }}
